# Generated by Django 3.1.1 on 2020-09-08 16:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DimagiUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('profile_picture', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100)),
                ('country_name', models.CharField(max_length=100)),
                ('longitude', models.DecimalField(decimal_places=5, max_digits=5)),
                ('latitude', models.DecimalField(decimal_places=5, max_digits=5)),
                ('current', models.BooleanField(default=True)),
                ('time', models.DateTimeField(default=datetime.date.today)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whereami.dimagiuser')),
            ],
        ),
    ]
