# Generated by Django 3.1.1 on 2020-09-08 17:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('whereami', '0002_auto_20200908_1707'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DimagiUser',
            new_name='User',
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(decimal_places=5, max_digits=8),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(decimal_places=5, max_digits=8),
        ),
        migrations.AlterField(
            model_name='location',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
